import {
  EXPANDED_TPE_AMOUNT,
  FIRST_APRON,
  LEAGUE_YEAR,
  MIN_TEAM_SALARY,
  ROSTER_MAX_STANDARD,
  ROSTER_MAX_TWO_WAY,
  ROSTER_MIN_SEASON,
  SALARY_CAP,
  SECOND_APRON,
  TPE_BUFFER,
  TRADE_CASH_LIMIT,
} from "./constants";
import { salaryFor } from "./capsheet";
import { usd, usdM } from "./format";
import { checkStepien, ownsPick, parsePickId } from "./picks";
import type {
  Player,
  RuleCheck,
  TeamCapSheet,
  TeamCode,
  TradeContext,
  TradeProposal,
  TradeSide,
  Verdict,
} from "./types";

/**
 * R1 — the 2023-CBA salary-matching allowance for a team whose post-trade
 * salary is at or below the first apron. Max incoming for `out` outgoing:
 * the greater of 125% + $250K, and the lesser of 200% + $250K and
 * out + the expanded-TPE amount ($9,096,000 in 2026-27).
 */
export function maxIncomingBelowApron(out: number): number {
  return Math.max(
    1.25 * out + TPE_BUFFER,
    Math.min(2 * out + TPE_BUFFER, out + EXPANDED_TPE_AMOUNT),
  );
}

type Regime = "room" | "below-apron" | "first-apron" | "second-apron";

interface SideComputed {
  side: TradeSide;
  sheet: TeamCapSheet;
  outPlayers: Player[];
  /** Outgoing salaries that count for matching (standard/rookie/min; no two-ways). */
  outMatched: Player[];
  outTwoWays: Player[];
  outSalary: number;
  inSalary: number;
  inMatched: Player[];
  inTwoWays: Player[];
  postTotal: number;
  regime: Regime;
  /** Trade could be completed inside cap room — matching rules don't bind. */
  roomAbsorbed: boolean;
  aggregated: boolean;
  sentPickYears: number[];
  receivedPickYears: number[];
}

function isMatchable(p: Player): boolean {
  return p.contractType !== "two-way" && p.contractType !== "dead";
}

function playerNames(players: Player[]): string {
  return players.map((p) => p.name).join(" + ") || "nothing";
}

function regimeFor(postTotal: number): Regime {
  if (postTotal > SECOND_APRON) return "second-apron";
  if (postTotal > FIRST_APRON) return "first-apron";
  if (postTotal <= SALARY_CAP) return "room";
  return "below-apron";
}

/** Allowance generated by a single outgoing salary under a regime. */
function singleAllowance(out: number, regime: Regime): number {
  if (regime === "first-apron" || regime === "second-apron") return out;
  return maxIncomingBelowApron(out);
}

export function validateTrade(proposal: TradeProposal, ctx: TradeContext): Verdict {
  const checks: RuleCheck[] = [];
  const [a, b] = proposal.sides;

  // ---- Structure ---------------------------------------------------------
  const structureProblems: string[] = [];
  if (a.team === b.team) structureProblems.push("both sides are the same team");
  for (const side of [a, b]) {
    if (!ctx.capSheets[side.team]) structureProblems.push(`no cap sheet loaded for ${side.team}`);
    const assets =
      side.playerIds.length + (side.pickIds?.length ?? 0) + ((side.cash ?? 0) > 0 ? 1 : 0);
    if (assets === 0) structureProblems.push(`${side.team} sends nothing`);
  }
  checks.push({
    id: "structure",
    team: "",
    status: structureProblems.length ? "fail" : "pass",
    headline: structureProblems.length
      ? "Trade structure: invalid"
      : `Two-team trade: ${a.team} ↔ ${b.team}`,
    detail: structureProblems.length
      ? `This proposal can't be evaluated: ${structureProblems.join("; ")}.`
      : `Each side sends at least one asset. Evaluated under the ${proposal.leagueYear} CBA rules with the rosters as seeded.`,
  });
  if (structureProblems.length) return { legal: false, checks };

  // ---- Resolve + integrity ----------------------------------------------
  const resolved: SideComputed[] = [];
  let integrityFailed = false;

  for (const side of [a, b]) {
    const sheet = ctx.capSheets[side.team]!;
    const uniqueIds = [...new Set(side.playerIds)];
    const outPlayers: Player[] = [];
    for (const id of uniqueIds) {
      const p = sheet.players.find((pl) => pl.playerId === id);
      if (!p) {
        checks.push({
          id: "roster-integrity",
          team: side.team,
          status: "fail",
          headline: `Unknown player id "${id}" on ${side.team}`,
          detail: `Player id "${id}" is not on the seeded ${side.team} roster, so the trade can't be evaluated.`,
        });
        integrityFailed = true;
        continue;
      }
      if (p.contractType === "dead") {
        checks.push({
          id: "roster-integrity",
          team: side.team,
          status: "fail",
          headline: `${p.name} is a dead-money cap hit`,
          detail: `${p.name}'s ${usd(salaryFor(p, proposal.leagueYear))} is a waived/stretched cap charge, not a tradeable contract.`,
        });
        integrityFailed = true;
        continue;
      }
      outPlayers.push(p);
    }

    const outMatched = outPlayers.filter(isMatchable);
    const outTwoWays = outPlayers.filter((p) => p.contractType === "two-way");
    const outSalary = outMatched.reduce((s, p) => s + salaryFor(p, proposal.leagueYear), 0);

    resolved.push({
      side,
      sheet,
      outPlayers,
      outMatched,
      outTwoWays,
      outSalary,
      inSalary: 0,
      inMatched: [],
      inTwoWays: [],
      postTotal: 0,
      regime: "below-apron",
      roomAbsorbed: false,
      aggregated: false,
      sentPickYears: [],
      receivedPickYears: [],
    });
  }
  if (integrityFailed) return { legal: false, checks };

  const [sa, sb] = resolved as [SideComputed, SideComputed];
  sa.inSalary = sb.outSalary;
  sb.inSalary = sa.outSalary;
  sa.inMatched = sb.outMatched;
  sb.inMatched = sa.outMatched;
  sa.inTwoWays = sb.outTwoWays;
  sb.inTwoWays = sa.outTwoWays;

  for (const s of resolved) {
    s.postTotal = s.sheet.totalSalary - s.outSalary + s.inSalary;
    s.regime = regimeFor(s.postTotal);
    s.roomAbsorbed = s.regime === "room";
    const largestOut = Math.max(0, ...s.outMatched.map((p) => salaryFor(p, proposal.leagueYear)));
    s.aggregated =
      !s.roomAbsorbed &&
      s.outMatched.length >= 2 &&
      s.inSalary > singleAllowance(largestOut, s.regime);
  }

  // Picks: each side may send its own firsts.
  for (const s of resolved) {
    const other = s === sa ? sb : sa;
    for (const id of s.side.pickIds ?? []) {
      const parsed = parsePickId(id);
      if (!parsed || parsed.team !== s.side.team) {
        checks.push({
          id: "pick-integrity",
          team: s.side.team,
          status: "fail",
          headline: `Pick "${id}" isn't ${s.side.team}'s to trade`,
          detail: `v1 models teams trading their own future firsts ("TEAM-YYYY-1st"). "${id}" doesn't parse as a ${s.side.team} first.`,
        });
        continue;
      }
      if (!ownsPick(ctx.picks?.[s.side.team], parsed.year)) {
        checks.push({
          id: "pick-integrity",
          team: s.side.team,
          status: "fail",
          headline: `${s.side.team} no longer owns its ${parsed.year} first`,
          detail: `The seeded pick ledger shows ${s.side.team}'s ${parsed.year} first-round pick already traded away, so it can't be sent again.`,
        });
        continue;
      }
      s.sentPickYears.push(parsed.year);
      other.receivedPickYears.push(parsed.year);
    }
  }

  // ---- Per-team rule ledger ----------------------------------------------
  for (const s of resolved) {
    const t = s.side.team;
    const year = proposal.leagueYear;

    // R1/R2/R3 — salary matching
    if (s.inSalary === 0) {
      checks.push({
        id: "salary-matching",
        team: t,
        status: "pass",
        headline: `Salary matching: no incoming salary`,
        detail: `${t} takes back no salary in this deal, so the traded-player matching rules impose no limit.`,
      });
    } else if (s.roomAbsorbed) {
      checks.push({
        id: "salary-matching",
        team: t,
        status: "pass",
        headline: `Salary matching: absorbed into cap room (${usdM(s.inSalary)} in, finishes ${usdM(s.postTotal)})`,
        detail: `${t} finishes this trade at ${usd(s.postTotal)}, at or under the ${usd(SALARY_CAP)} cap. The incoming ${usd(s.inSalary)} fits inside cap room, so percentage-matching rules don't bind.`,
      });
    } else if (s.regime === "second-apron" || s.regime === "first-apron") {
      const apron = s.regime === "second-apron" ? SECOND_APRON : FIRST_APRON;
      const apronName = s.regime === "second-apron" ? "second apron" : "first apron";
      const ok = s.inSalary <= s.outSalary;
      checks.push({
        id: "salary-matching",
        team: t,
        status: ok ? "pass" : "fail",
        headline: ok
          ? `Salary matching (${apronName}): OK (${usdM(s.inSalary)} in ≤ ${usdM(s.outSalary)} out)`
          : `Salary matching (${apronName}): over by ${usd(s.inSalary - s.outSalary)}`,
        detail: `${t} finishes this trade at ${usd(s.postTotal)}, above the ${apronName} (${usd(apron)}). Apron teams may take back at most 100% of outgoing salary: sending ${usd(s.outSalary)} allows ${usd(s.outSalary)} back; the deal brings in ${usd(s.inSalary)}.${ok ? "" : " Reduce incoming salary or send more out."}`,
      });
    } else {
      const limit = maxIncomingBelowApron(s.outSalary);
      const ok = s.inSalary <= limit;
      checks.push({
        id: "salary-matching",
        team: t,
        status: ok ? "pass" : "fail",
        headline: ok
          ? `Salary matching: OK (${usdM(s.inSalary)} in vs ${usdM(limit)} allowed)`
          : `Salary matching: over by ${usd(s.inSalary - limit)}`,
        detail: `Outgoing ${usd(s.outSalary)} allows up to ${usd(limit)} back — the greater of 125% + $250K (${usd(1.25 * s.outSalary + TPE_BUFFER)}) and the lesser of 200% + $250K (${usd(2 * s.outSalary + TPE_BUFFER)}) and outgoing + ${usd(EXPANDED_TPE_AMOUNT)} (${usd(s.outSalary + EXPANDED_TPE_AMOUNT)}). ${t} takes back ${usd(s.inSalary)}.`,
      });
    }

    // R3 — aggregation (and its second-apron prohibition)
    if (s.outMatched.length < 2 || s.inSalary === 0 || s.roomAbsorbed) {
      checks.push({
        id: "aggregation",
        team: t,
        status: "n/a",
        headline: "Aggregation: not in play",
        detail:
          s.outMatched.length < 2
            ? `${t} sends ${s.outMatched.length === 1 ? "a single matched salary" : "no matched salary"}, so nothing is aggregated.`
            : s.roomAbsorbed
              ? `${t} absorbs the return into cap room, so no salaries are aggregated for matching.`
              : `${t} takes back no salary, so nothing is aggregated.`,
      });
    } else if (!s.aggregated) {
      checks.push({
        id: "aggregation",
        team: t,
        status: "pass",
        headline: "Aggregation: not required for this return",
        detail: `${t} sends ${s.outMatched.length} players, but the incoming ${usd(s.inSalary)} fits within the allowance generated by the largest single outgoing salary alone — the deal doesn't rely on aggregating salaries.`,
      });
    } else if (s.regime === "second-apron") {
      checks.push({
        id: "apron2-aggregation",
        team: t,
        status: "fail",
        headline: `Aggregation barred above the second apron`,
        detail: `${t} finishes this trade at ${usd(s.postTotal)}, above the ${usd(SECOND_APRON)} second apron, and second-apron teams cannot aggregate two or more outgoing salaries (${playerNames(s.outMatched)}) to take back a bigger one. Shed salary below the apron or restructure to single-player matching.`,
      });
    } else {
      checks.push({
        id: "aggregation",
        team: t,
        status: "pass",
        headline: `Aggregating ${s.outMatched.length} salaries (legal, triggers hard cap)`,
        detail: `${t} combines ${playerNames(s.outMatched)} (${usd(s.outSalary)}) to match the incoming ${usd(s.inSalary)}. Legal below the second apron — see the hard-cap flag below.`,
      });
    }

    // R5 — cash
    const cash = s.side.cash ?? 0;
    const ledger = ctx.cashLedger?.[t] ?? { sent: 0, received: 0 };
    const otherCash = (s === sa ? sb : sa).side.cash ?? 0;
    if (cash <= 0 && otherCash <= 0) {
      checks.push({
        id: "cash-limit",
        team: t,
        status: "n/a",
        headline: "Cash: none in this deal",
        detail: `No cash moves in this trade. ${t} has ${usd(TRADE_CASH_LIMIT - ledger.sent)} of its ${year} send limit and ${usd(TRADE_CASH_LIMIT - ledger.received)} of its receive limit remaining.`,
      });
    } else if (cash > 0 && s.regime === "second-apron") {
      checks.push({
        id: "apron2-cash",
        team: t,
        status: "fail",
        headline: "Second-apron teams cannot send cash",
        detail: `${t} finishes this trade at ${usd(s.postTotal)}, above the ${usd(SECOND_APRON)} second apron. Sending ${usd(cash)} is prohibited at that level.`,
      });
    } else {
      const sendOver = ledger.sent + cash - TRADE_CASH_LIMIT;
      const recvOver = ledger.received + otherCash - TRADE_CASH_LIMIT;
      const over = Math.max(sendOver, recvOver);
      const parts: string[] = [];
      if (cash > 0)
        parts.push(
          `sends ${usd(cash)} (${usd(ledger.sent)} already sent this league year; annual limit ${usd(TRADE_CASH_LIMIT)})`,
        );
      if (otherCash > 0)
        parts.push(
          `receives ${usd(otherCash)} (${usd(ledger.received)} already received; annual limit ${usd(TRADE_CASH_LIMIT)})`,
        );
      checks.push({
        id: "cash-limit",
        team: t,
        status: over > 0 ? "fail" : "pass",
        headline:
          over > 0
            ? `Cash: over the ${year} annual limit by ${usd(over)}`
            : `Cash: within the ${year} annual limits`,
        detail: `${t} ${parts.join(" and ")}. Sent and received cash are tracked separately, each capped at ${usd(TRADE_CASH_LIMIT)} per league year.`,
      });
    }

    // R4 — roster bounds
    const outStandard = s.outMatched.length;
    const inStandard = s.inMatched.length;
    const postStandard = s.sheet.standardCount - outStandard + inStandard;
    const rosterStatus = postStandard > ROSTER_MAX_STANDARD ? "fail" : postStandard < ROSTER_MIN_SEASON ? "warning" : "pass";
    checks.push({
      id: "roster-bounds",
      team: t,
      status: rosterStatus,
      headline:
        rosterStatus === "fail"
          ? `Roster: ${postStandard} standard contracts exceeds the ${ROSTER_MAX_STANDARD}-man limit`
          : rosterStatus === "warning"
            ? `Roster: ${postStandard} standard contracts (below the in-season floor of ${ROSTER_MIN_SEASON})`
            : `Roster: ${postStandard} standard contracts`,
      detail:
        rosterStatus === "fail"
          ? `${t} would go from ${s.sheet.standardCount} to ${postStandard} standard contracts; the maximum is ${ROSTER_MAX_STANDARD}. A player must be waived or added to the outgoing side.`
          : rosterStatus === "warning"
            ? `${t} would drop to ${postStandard} standard contracts. Teams must carry at least ${ROSTER_MIN_SEASON} during the season (a two-week grace window applies), so a signing would be required.`
            : `${t} moves from ${s.sheet.standardCount} to ${postStandard} standard contracts — inside the ${ROSTER_MIN_SEASON}–${ROSTER_MAX_STANDARD} band.`,
    });

    const postTwoWay = s.sheet.twoWayCount - s.outTwoWays.length + s.inTwoWays.length;
    if (s.outTwoWays.length || s.inTwoWays.length) {
      checks.push({
        id: "two-way-limit",
        team: t,
        status: postTwoWay > ROSTER_MAX_TWO_WAY ? "fail" : "pass",
        headline:
          postTwoWay > ROSTER_MAX_TWO_WAY
            ? `Two-way slots: ${postTwoWay} exceeds the limit of ${ROSTER_MAX_TWO_WAY}`
            : `Two-way slots: ${postTwoWay} of ${ROSTER_MAX_TWO_WAY}`,
        detail: `${t} would carry ${postTwoWay} two-way players after the trade; the maximum is ${ROSTER_MAX_TWO_WAY}.`,
      });
    }

    // R4 — two-ways excluded from matching
    if (s.outTwoWays.length) {
      const withTwoWay =
        s.outSalary + s.outTwoWays.reduce((sum, p) => sum + salaryFor(p, year), 0);
      const matchingFailed = s.inSalary > 0 && !s.roomAbsorbed &&
        (s.regime === "first-apron" || s.regime === "second-apron"
          ? s.inSalary > s.outSalary
          : s.inSalary > maxIncomingBelowApron(s.outSalary));
      const wouldPassWithTwoWay =
        s.regime === "first-apron" || s.regime === "second-apron"
          ? s.inSalary <= withTwoWay
          : s.inSalary <= maxIncomingBelowApron(withTwoWay);
      if (matchingFailed && wouldPassWithTwoWay) {
        checks.push({
          id: "two-way-matching",
          team: t,
          status: "fail",
          headline: `Two-way salary can't be used for matching`,
          detail: `Counting ${playerNames(s.outTwoWays)}'s two-way salary would make the math work, but two-way contracts are excluded from salary matching and from team salary. Only ${usd(s.outSalary)} of standard salary counts.`,
        });
      } else {
        checks.push({
          id: "two-way-matching",
          team: t,
          status: "n/a",
          headline: `Two-way contracts excluded from matching`,
          detail: `${playerNames(s.outTwoWays)} moves on a two-way contract: tradeable, but contributes $0 to salary matching and $0 to team salary.`,
        });
      }
    }

    // R8 — player restrictions
    const restrictionRows: { status: "warning" | "fail"; text: string }[] = [];
    for (const p of s.outPlayers) {
      for (const r of p.tradeRestrictions ?? []) {
        if (r === "no-trade") {
          restrictionRows.push({
            status: "warning",
            text: `${p.name} has a no-trade clause — the deal requires his written consent.`,
          });
        } else if (r === "recently-signed") {
          restrictionRows.push({
            status: "fail",
            text: `${p.name} was recently signed and cannot be traded yet${p.returnEligibleDate ? ` (trade-eligible ${p.returnEligibleDate})` : ""}.`,
          });
        } else if (r === "cannot-aggregate" && s.aggregated) {
          restrictionRows.push({
            status: "fail",
            text: `${p.name} cannot have his salary aggregated with others in a trade, and this deal aggregates ${playerNames(s.outMatched)}.`,
          });
        }
      }
    }
    const worst = restrictionRows.some((r) => r.status === "fail")
      ? "fail"
      : restrictionRows.length
        ? "warning"
        : "pass";
    checks.push({
      id: "player-restrictions",
      team: t,
      status: worst,
      headline:
        worst === "pass"
          ? "Player restrictions: none triggered"
          : worst === "warning"
            ? "Player restrictions: consent required"
            : "Player restrictions: blocked",
      detail: restrictionRows.length
        ? restrictionRows.map((r) => r.text).join(" ")
        : `No player ${t} sends carries a no-trade clause, a recently-signed freeze, or an aggregation restriction.`,
    });

    // R7 — Stepien
    if (s.sentPickYears.length || s.receivedPickYears.length) {
      const result = checkStepien(ctx.picks?.[t], s.sentPickYears, s.receivedPickYears);
      checks.push({
        id: "stepien",
        team: t,
        status: result.ok ? "pass" : "fail",
        headline: result.ok
          ? "Stepien rule: no consecutive drafts without a first"
          : `Stepien rule: no first in ${result.gaps.map((g) => `${g[0]} & ${g[1]}`).join(", ")}`,
        detail: result.ok
          ? `After the trade ${t} still has a first-round pick (owned or swap-encumbered) often enough to avoid back-to-back empty drafts. Missing years: ${result.missingYears.length ? result.missingYears.join(", ") : "none"}.`
          : `A team may not leave itself without a first-round pick in consecutive future drafts. After this trade ${t} would have no first in ${result.gaps.map((g) => `${g[0]} and ${g[1]}`).join("; ")} (swap-encumbered years still count as having a pick).`,
      });
    } else {
      checks.push({
        id: "stepien",
        team: t,
        status: "n/a",
        headline: "Stepien rule: no picks in this deal",
        detail: `${t} sends and receives no first-round picks here, so pick-protection rules aren't engaged.`,
      });
    }

    // R6 — hard-cap triggers (warnings, not failures)
    const apron1Triggers: string[] = [];
    if (!s.roomAbsorbed && s.inSalary > s.outSalary && s.postTotal <= FIRST_APRON) {
      apron1Triggers.push(
        `taking back more than 100% of outgoing salary (${usd(s.inSalary)} in vs ${usd(s.outSalary)} out) via the expanded traded-player exception`,
      );
    }
    checks.push({
      id: "hardcap-apron1",
      team: t,
      status: apron1Triggers.length ? "warning" : "pass",
      headline: apron1Triggers.length
        ? `Hard cap triggered at the first apron (${usdM(FIRST_APRON)})`
        : "First-apron hard cap: not triggered",
      detail: apron1Triggers.length
        ? `This trade is legal, but ${apron1Triggers.join(" and ")} hard-caps ${t} at the first apron (${usd(FIRST_APRON)}) for the rest of ${LEAGUE_YEAR}. ${t} finishes at ${usd(s.postTotal)}, leaving ${usd(FIRST_APRON - s.postTotal)} of headroom under its new ceiling.`
        : `${t} doesn't take back more than 100% of outgoing salary, so no first-apron hard cap is created by this trade.`,
    });

    const apron2Triggers: string[] = [];
    if (s.aggregated && s.regime !== "second-apron") {
      apron2Triggers.push(`aggregating ${playerNames(s.outMatched)}`);
    }
    if (cash > 0 && s.regime !== "second-apron") {
      apron2Triggers.push(`sending ${usd(cash)} in cash`);
    }
    checks.push({
      id: "hardcap-apron2",
      team: t,
      status: apron2Triggers.length ? "warning" : "pass",
      headline: apron2Triggers.length
        ? `Hard cap triggered at the second apron (${usdM(SECOND_APRON)})`
        : "Second-apron hard cap: not triggered",
      detail: apron2Triggers.length
        ? `This trade is legal, but ${apron2Triggers.join(" and ")} hard-caps ${t} at the second apron (${usd(SECOND_APRON)}) for the rest of ${LEAGUE_YEAR}.${apron1Triggers.length ? " The stricter first-apron cap above binds first." : ""} ${t} finishes at ${usd(s.postTotal)}.`
        : `${t} neither aggregates salaries nor sends cash, so no second-apron hard cap is created by this trade.`,
    });

    // Salary floor (informational)
    checks.push({
      id: "salary-floor",
      team: t,
      status: s.postTotal < MIN_TEAM_SALARY ? "warning" : "pass",
      headline:
        s.postTotal < MIN_TEAM_SALARY
          ? `Team salary ${usd(MIN_TEAM_SALARY - s.postTotal)} below the floor`
          : "Salary floor: satisfied",
      detail:
        s.postTotal < MIN_TEAM_SALARY
          ? `${t} would sit at ${usd(s.postTotal)}, under the ${usd(MIN_TEAM_SALARY)} minimum team salary. Legal to complete, but the shortfall must be made up by season's end (paid to the players on the roster).`
          : `${t} finishes at ${usd(s.postTotal)}, above the ${usd(MIN_TEAM_SALARY)} minimum team salary.`,
    });
  }

  return { legal: !checks.some((c) => c.status === "fail"), checks };
}
